/**
 * Type definitions for city+service combo pages (e.g., "Roofing in Oakland").
 * These are drill-down pages linked from the generalized city pages.
 */

import type { HeroProps, SectionBlock } from './service-page-types';

export interface CityServicePageData {
  city: string;
  county: string;
  state: string;
  citySlug: string;
  countySlug: string;
  serviceSlug: string;
  serviceName: string;
  title: string;
  description: string;
  hero: HeroProps;
  sections: SectionBlock[];
  localFaqs?: Array<{ question: string; answer: string }>;
  neighborhoods?: string[];
  nearbyCityServices?: Array<{ name: string; href: string }>;
  /** Long-form HTML content rendered between hero and sections.
   *  Drives E-E-A-T + AI citation. ~1500-2200 words of city-specific
   *  permit/code/climate/pricing detail. Auto-generated by the SEO loop. */
  longFormContent?: string;
  /** One-sentence bridge between hero and long-form content. */
  longFormIntro?: string;
}
