/**
 * Seed data for all 29 Bay Area cities in the pSEO system.
 * Real neighborhood names, median home prices, and population data.
 *
 * 29 cities across 5 counties:
 * - Alameda (5): Oakland, Berkeley, Fremont, Hayward, San Leandro
 * - Contra Costa (5): Antioch, Concord, Richmond, San Ramon, Walnut Creek
 * - Marin (4): Larkspur, Mill Valley, Novato, San Rafael
 * - Napa (5): Napa, American Canyon, St. Helena, Calistoga, Yountville
 * - Santa Clara (10): San Jose, Palo Alto, Mountain View, Sunnyvale, Cupertino,
 *                      Santa Clara, Saratoga, Los Gatos, Campbell, Milpitas
 */

export interface CitySeed {
  city: string;
  county: string;
  state: string;
  slug: string;
  countySlug: string;
  neighborhoods: string[];
  medianHomePrice: string;
  population: string;
  keyFeature: string;
}

export const CITY_SEEDS: CitySeed[] = [
  // ── Alameda County ────────────────────────────────────────────────────
  {
    city: 'Oakland',
    county: 'Alameda',
    state: 'CA',
    slug: 'oakland',
    countySlug: 'alameda',
    neighborhoods: [
      'Rockridge',
      'Temescal',
      'Montclair',
      'Piedmont Avenue',
      'Grand Lake',
      'Adams Point',
      'Lakeshore',
      'Crocker Highlands',
      'Glenview',
      'Dimond',
    ],
    medianHomePrice: '$850,000',
    population: '433,031',
    keyFeature: 'largest city in the East Bay with a thriving arts and dining scene',
  },
  {
    city: 'Berkeley',
    county: 'Alameda',
    state: 'CA',
    slug: 'berkeley',
    countySlug: 'alameda',
    neighborhoods: [
      'North Berkeley',
      'Elmwood',
      'Claremont',
      'Thousand Oaks',
      'Westbrae',
      'Berkeley Hills',
      'South Berkeley',
      'Gourmet Ghetto',
    ],
    medianHomePrice: '$1,400,000',
    population: '124,321',
    keyFeature: 'home to UC Berkeley and the Gourmet Ghetto',
  },
  {
    city: 'Fremont',
    county: 'Alameda',
    state: 'CA',
    slug: 'fremont',
    countySlug: 'alameda',
    neighborhoods: [
      'Niles',
      'Mission San Jose',
      'Irvington',
      'Warm Springs',
      'Centerville',
      'Glenmoor',
      'Sundale',
      'Parkmont',
    ],
    medianHomePrice: '$1,500,000',
    population: '230,504',
    keyFeature: 'home to Tesla\'s Fremont Factory and top-rated schools',
  },
  {
    city: 'Hayward',
    county: 'Alameda',
    state: 'CA',
    slug: 'hayward',
    countySlug: 'alameda',
    neighborhoods: [
      'Hayward Hills',
      'Downtown Hayward',
      'South Hayward',
      'Cherryland',
      'Fairview',
      'Harder-Tennyson',
      'Mission Hills',
    ],
    medianHomePrice: '$880,000',
    population: '162,954',
    keyFeature: 'gateway to the East Bay hills with Cal State University East Bay',
  },
  {
    city: 'San Leandro',
    county: 'Alameda',
    state: 'CA',
    slug: 'san-leandro',
    countySlug: 'alameda',
    neighborhoods: [
      'Estudillo Estates',
      'Bay-O-Vista',
      'Washington Manor',
      'Marina',
      'Broadmoor',
      'Downtown San Leandro',
      'Floresta Gardens',
    ],
    medianHomePrice: '$900,000',
    population: '91,361',
    keyFeature: 'waterfront living along the San Francisco Bay with easy BART access',
  },

  // ── Contra Costa County ───────────────────────────────────────────────
  {
    city: 'Antioch',
    county: 'Contra Costa',
    state: 'CA',
    slug: 'antioch',
    countySlug: 'contra-costa',
    neighborhoods: [
      'Lone Tree',
      'Deer Valley',
      'Black Diamond',
      'Sycamore',
      'Prewett Ranch',
      'Sand Creek',
      'Downtown Antioch',
    ],
    medianHomePrice: '$620,000',
    population: '115,291',
    keyFeature: 'fastest-growing East Bay city on the San Joaquin River Delta',
  },
  {
    city: 'Concord',
    county: 'Contra Costa',
    state: 'CA',
    slug: 'concord',
    countySlug: 'contra-costa',
    neighborhoods: [
      'Dana Estates',
      'Lime Ridge',
      'Pine Hollow',
      'Four Corners',
      'Holbrook',
      'Ellis Lake',
      'Todos Santos',
      'Cowell',
    ],
    medianHomePrice: '$750,000',
    population: '129,295',
    keyFeature: 'central Contra Costa hub home to the Concord Pavilion and Todos Santos Plaza',
  },
  {
    city: 'Richmond',
    county: 'Contra Costa',
    state: 'CA',
    slug: 'richmond',
    countySlug: 'contra-costa',
    neighborhoods: [
      'Point Richmond',
      'Marina Bay',
      'El Cerrito Hills',
      'Hilltop',
      'Iron Triangle',
      'Atchison Village',
      'East Richmond Heights',
    ],
    medianHomePrice: '$650,000',
    population: '116,448',
    keyFeature: 'waterfront city with Rosie the Riveter National Park and Bay Trail access',
  },
  {
    city: 'San Ramon',
    county: 'Contra Costa',
    state: 'CA',
    slug: 'san-ramon',
    countySlug: 'contra-costa',
    neighborhoods: [
      'Dougherty Valley',
      'Gale Ranch',
      'Canyon Lakes',
      'Windemere',
      'Westside',
      'Twin Creeks',
      'Old Ranch',
    ],
    medianHomePrice: '$1,600,000',
    population: '84,605',
    keyFeature: 'headquarters to Chevron and home to top-rated San Ramon Valley schools',
  },
  {
    city: 'Walnut Creek',
    county: 'Contra Costa',
    state: 'CA',
    slug: 'walnut-creek',
    countySlug: 'contra-costa',
    neighborhoods: [
      'Northgate',
      'Rossmoor',
      'Saranap',
      'Parkmead',
      'Lakewood',
      'Alamo Creek',
      'Downtown Walnut Creek',
      'Indian Valley',
    ],
    medianHomePrice: '$1,200,000',
    population: '71,903',
    keyFeature: 'upscale shopping and dining hub with Mt. Diablo trailhead access',
  },

  // ── Marin County ──────────────────────────────────────────────────────
  {
    city: 'Larkspur',
    county: 'Marin',
    state: 'CA',
    slug: 'larkspur',
    countySlug: 'marin',
    neighborhoods: [
      'Greenbrae',
      'Bon Air',
      'Baltimore Park',
      'Murray Park',
      'Hillview',
      'Downtown Larkspur',
    ],
    medianHomePrice: '$1,800,000',
    population: '13,014',
    keyFeature: 'charming creek-side town with the Larkspur Ferry to San Francisco',
  },
  {
    city: 'Mill Valley',
    county: 'Marin',
    state: 'CA',
    slug: 'mill-valley',
    countySlug: 'marin',
    neighborhoods: [
      'Tamalpais Valley',
      'Strawberry',
      'Alto',
      'Homestead Valley',
      'Blithedale Canyon',
      'Scott Highlands',
      'Downtown Mill Valley',
    ],
    medianHomePrice: '$2,100,000',
    population: '14,854',
    keyFeature: 'nestled at the base of Mt. Tamalpais with world-class hiking and redwoods',
  },
  {
    city: 'Novato',
    county: 'Marin',
    state: 'CA',
    slug: 'novato',
    countySlug: 'marin',
    neighborhoods: [
      'Hamilton',
      'Ignacio',
      'Loma Verde',
      'Bel Marin Keys',
      'Indian Valley',
      'Pacheco Valle',
      'Downtown Novato',
    ],
    medianHomePrice: '$1,200,000',
    population: '56,116',
    keyFeature: 'northernmost Marin city with spacious lots and rolling hillside neighborhoods',
  },
  {
    city: 'San Rafael',
    county: 'Marin',
    state: 'CA',
    slug: 'san-rafael',
    countySlug: 'marin',
    neighborhoods: [
      'Dominican',
      'Gerstle Park',
      'Sun Valley',
      'Peacock Gap',
      'Terra Linda',
      'Lucas Valley',
      'Downtown San Rafael',
      'Canal District',
    ],
    medianHomePrice: '$1,300,000',
    population: '62,022',
    keyFeature: 'Marin County seat and home to the Frank Lloyd Wright-designed Marin Civic Center',
  },

  // ── Napa County ───────────────────────────────────────────────────────
  {
    city: 'Napa',
    county: 'Napa',
    state: 'CA',
    slug: 'napa',
    countySlug: 'napa',
    neighborhoods: [
      'Browns Valley',
      'Old Town Napa',
      'Westwood',
      'Bel Aire',
      'Silverado',
      'Alta Heights',
      'Oxbow District',
    ],
    medianHomePrice: '$850,000',
    population: '79,657',
    keyFeature: 'heart of Napa Valley wine country with a revitalized downtown riverfront',
  },
  {
    city: 'American Canyon',
    county: 'Napa',
    state: 'CA',
    slug: 'american-canyon',
    countySlug: 'napa',
    neighborhoods: [
      'Canyon Oaks',
      'Town Center',
      'Napa Junction',
      'Elliot Ranch',
      'Green Island',
    ],
    medianHomePrice: '$720,000',
    population: '24,436',
    keyFeature: 'gateway to Napa Valley with the wetlands of the American Canyon Preserve',
  },
  {
    city: 'St. Helena',
    county: 'Napa',
    state: 'CA',
    slug: 'st-helena',
    countySlug: 'napa',
    neighborhoods: [
      'Downtown St. Helena',
      'Spring Mountain',
      'Meadowood',
      'Pope Valley',
      'Sulphur Springs',
    ],
    medianHomePrice: '$2,500,000',
    population: '6,070',
    keyFeature: 'iconic Napa Valley main street town surrounded by world-renowned vineyards',
  },
  {
    city: 'Calistoga',
    county: 'Napa',
    state: 'CA',
    slug: 'calistoga',
    countySlug: 'napa',
    neighborhoods: [
      'Downtown Calistoga',
      'Silverado Trail',
      'Knights Valley',
      'Diamond Mountain',
    ],
    medianHomePrice: '$1,200,000',
    population: '5,770',
    keyFeature: 'hot springs resort town at the northern tip of Napa Valley',
  },
  {
    city: 'Yountville',
    county: 'Napa',
    state: 'CA',
    slug: 'yountville',
    countySlug: 'napa',
    neighborhoods: [
      'Downtown Yountville',
      'Veterans Home',
      'Washington Street',
      'Yount Mill Road',
    ],
    medianHomePrice: '$1,800,000',
    population: '3,004',
    keyFeature: 'Michelin-starred culinary capital of Napa Valley',
  },

  // ── Santa Clara County ────────────────────────────────────────────────
  {
    city: 'San Jose',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'san-jose',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Willow Glen',
      'Rose Garden',
      'Almaden Valley',
      'Cambrian',
      'Berryessa',
      'Evergreen',
      'Silver Creek',
      'Blossom Valley',
      'Naglee Park',
      'SoFA District',
    ],
    medianHomePrice: '$1,350,000',
    population: '1,013,240',
    keyFeature: 'capital of Silicon Valley and the largest city in the Bay Area',
  },
  {
    city: 'Palo Alto',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'palo-alto',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Crescent Park',
      'Old Palo Alto',
      'Professorville',
      'College Terrace',
      'Midtown',
      'Barron Park',
      'Green Acres',
      'Charleston Meadows',
    ],
    medianHomePrice: '$3,500,000',
    population: '68,572',
    keyFeature: 'home to Stanford University and the birthplace of Silicon Valley',
  },
  {
    city: 'Mountain View',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'mountain-view',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Old Mountain View',
      'Cuesta Park',
      'Rex Manor',
      'Waverly Park',
      'Gemello',
      'Shoreline West',
      'Sylvan Park',
    ],
    medianHomePrice: '$2,000,000',
    population: '82,376',
    keyFeature: 'home to Google headquarters and NASA Ames Research Center',
  },
  {
    city: 'Sunnyvale',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'sunnyvale',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Lakewood Village',
      'Birdland',
      'Ponderosa',
      'Cherry Chase',
      'Raynor Park',
      'Heritage District',
      'De Anza',
    ],
    medianHomePrice: '$1,900,000',
    population: '155,805',
    keyFeature: 'major tech hub home to Apple Park\'s neighbor and Juniper Networks',
  },
  {
    city: 'Cupertino',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'cupertino',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Rancho Rinconada',
      'Monta Vista',
      'Garden Gate',
      'Oak Valley',
      'Seven Springs',
      'Homestead Lanes',
    ],
    medianHomePrice: '$2,800,000',
    population: '60,170',
    keyFeature: 'home to Apple Park and top-ranked Cupertino Union School District',
  },
  {
    city: 'Santa Clara',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'santa-clara',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Old Quad',
      'Washington Square',
      'Rivermark Village',
      'Bowers',
      'Scott Boulevard',
      'Briarwood',
    ],
    medianHomePrice: '$1,700,000',
    population: '127,647',
    keyFeature: 'home to Levi\'s Stadium and Santa Clara University',
  },
  {
    city: 'Saratoga',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'saratoga',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Saratoga Village',
      'Saratoga Woods',
      'Golden Triangle',
      'Quito',
      'Brookglen',
      'Azule',
    ],
    medianHomePrice: '$3,200,000',
    population: '32,020',
    keyFeature: 'exclusive hillside community with top schools and Hakone Gardens',
  },
  {
    city: 'Los Gatos',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'los-gatos',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Downtown Los Gatos',
      'Shannon',
      'Blossom Hill',
      'Monte Sereno',
      'Almond Grove',
      'Los Gatos Meadows',
    ],
    medianHomePrice: '$2,600,000',
    population: '33,529',
    keyFeature: 'charming downtown village at the base of the Santa Cruz Mountains',
  },
  {
    city: 'Campbell',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'campbell',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Downtown Campbell',
      'Ainsley Park',
      'Hacienda',
      'Campbell Park',
      'San Tomas',
      'White Oaks',
    ],
    medianHomePrice: '$1,650,000',
    population: '43,925',
    keyFeature: 'walkable downtown with the Pruneyard and vibrant farmers market',
  },
  {
    city: 'Milpitas',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'milpitas',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Calaveras Hills',
      'Augustine',
      'Sunnyhills',
      'Murphy Ranch',
      'Serra Center',
      'Town Center',
    ],
    medianHomePrice: '$1,400,000',
    population: '80,430',
    keyFeature: 'booming tech corridor with the Great Mall and easy 680/880 freeway access',
  },
];

/**
 * Look up a city by its URL slug.
 * Returns undefined if no match is found.
 */
export function getCitySeed(citySlug: string): CitySeed | undefined {
  return CITY_SEEDS.find((c) => c.slug === citySlug);
}

/**
 * Get all cities in a given county.
 */
export function getCitiesByCounty(countySlug: string): CitySeed[] {
  return CITY_SEEDS.filter((c) => c.countySlug === countySlug);
}

/**
 * All unique county slugs in the system.
 */
export const COUNTY_SLUGS = [
  ...new Set(CITY_SEEDS.map((c) => c.countySlug)),
] as const;
