/**
 * Seed data for all 29 Bay Area cities in the pSEO system.
 * Real neighborhood names, median home prices, and population data.
 *
 * 29 cities across 5 counties:
 * - Alameda (5): Oakland, Berkeley, Fremont, Hayward, San Leandro
 * - Contra Costa (5): Antioch, Concord, Richmond, San Ramon, Walnut Creek
 * - Marin (4): Larkspur, Mill Valley, Novato, San Rafael
 * - Napa (5): Napa, American Canyon, St. Helena, Calistoga, Yountville
 * - Santa Clara (10): San Jose, Palo Alto, Mountain View, Sunnyvale, Cupertino,
 *                      Santa Clara, Saratoga, Los Gatos, Campbell, Milpitas
 */

export interface CitySeed {
  city: string;
  county: string;
  state: string;
  slug: string;
  countySlug: string;
  neighborhoods: string[];
  medianHomePrice: string;
  population: string;
  keyFeature: string;
  /** Dominant home era and styles, e.g. "1920s Craftsman bungalows, 1940s wartime cottages" */
  homeStyles: string;
  /** Local climate factor affecting exteriors */
  climateFactor: string;
  /** Common exterior issue in this city tied to climate/age */
  commonIssue: string;
  /** Price tier: 'budget' (<$700K) | 'mid' ($700K-$1.1M) | 'premium' ($1.1M-$1.8M) | 'luxury' (>$1.8M) */
  priceTier: 'budget' | 'mid' | 'premium' | 'luxury';
  /** Title 24 climate zone number (affects energy code requirements) */
  climateZone: number;
  /** Microclimate summary — temperature range, fog, wind */
  microclimate: string;
  /** Approximate housing stock era breakdown */
  eraBreakdown: string;
  /** Roofing-specific note for this city */
  roofingNote: string;
  /** Siding-specific note for this city */
  sidingNote: string;
  /** Window-specific note for this city */
  windowNote: string;
}

export const CITY_SEEDS: CitySeed[] = [
  // ── Alameda County ────────────────────────────────────────────────────
  {
    city: 'Oakland',
    county: 'Alameda',
    state: 'CA',
    slug: 'oakland',
    countySlug: 'alameda',
    neighborhoods: [
      'Rockridge',
      'Temescal',
      'Montclair',
      'Piedmont Avenue',
      'Grand Lake',
      'Adams Point',
      'Lakeshore',
      'Crocker Highlands',
      'Glenview',
      'Dimond',
    ],
    medianHomePrice: '$850,000',
    population: '433,031',
    keyFeature: 'largest city in the East Bay with a thriving arts and dining scene',
    homeStyles: '1920s Craftsman bungalows and Tudor Revivals in Rockridge/Temescal, 1940s wartime cottages in the flats, mid-century ranches in Montclair and the Hills, and contemporary infill near Lake Merritt',
    climateFactor: 'marine fog in West Oakland burning off by midday, 10-15°F warmer in the Hills, VHFHSZ fire zones above Highway 13, and salt air within 3 miles of the estuary',
    commonIssue: 'extensive dry rot in original redwood siding on pre-war homes, termite damage epidemic in older wood-frame stock, and curling composition shingles on south-facing Hills slopes from intense UV',
    priceTier: 'mid',
    climateZone: 3,
    microclimate: 'Three zones: foggy waterfront (55-72°F summers), moderate flats (58-78°F), and sunny Hills (62-85°F, frost possible). Annual rainfall 22-28 inches.',
    eraBreakdown: '35% pre-1940, 25% 1940-1960, 20% 1960-1985, 10% 1985-2010, 10% post-2010',
    roofingNote: 'Hills above Highway 13 are VHFHSZ — Class A fire-rated roofing and ember-resistant vents required. Composition shingles dominate flats. Flat/low-slope modified bitumen common on mid-century and commercial conversions. Permits take 2-4 weeks.',
    sidingNote: 'Original redwood shiplap on pre-1940 homes, many covered with asbestos shingles in the 1950s requiring abatement. T1-11 plywood failing on 1970s-80s East Oakland homes. West Oakland Victorian restorations may require matching original profiles per historic district guidelines.',
    windowNote: 'Noise from I-880, I-580, and BART drives demand for STC 35+ glazing. Victorian and Craftsman homes have original single-pane wood windows. Some neighborhoods have local historic designations requiring like-for-like profiles.',
  },
  {
    city: 'Berkeley',
    county: 'Alameda',
    state: 'CA',
    slug: 'berkeley',
    countySlug: 'alameda',
    neighborhoods: [
      'North Berkeley',
      'Elmwood',
      'Claremont',
      'Thousand Oaks',
      'Westbrae',
      'Berkeley Hills',
      'South Berkeley',
      'Gourmet Ghetto',
    ],
    medianHomePrice: '$1,400,000',
    population: '124,321',
    keyFeature: 'home to UC Berkeley and the Gourmet Ghetto',
    homeStyles: 'Brown Shingle style homes (1890s-1910s) in North Berkeley Hills and Elmwood, 1920s Stucco Tudor and Mediterranean Revival in Thousand Oaks, Craftsman bungalows in South Berkeley, and mid-century modern by notable architects (Maybeck, Ratcliff) in the Hills',
    climateFactor: 'sits directly in the Golden Gate fog funnel with persistent summer fog west of San Pablo Ave, extreme fire risk in Berkeley Hills (1991 fire), and 40+ mph Diablo wind gusts through Grizzly Peak',
    commonIssue: 'Brown Shingle cedar siding deterioration and moss growth on north faces, stucco cracking on 1920s-40s homes over wire lath, and termite damage in all pre-1960 wood-frame homes',
    priceTier: 'premium',
    climateZone: 3,
    microclimate: 'West Berkeley: heavy fog, 60-68°F summers. Central: 65-75°F. Hills: above fog line, 70-85°F, strong afternoon winds, frost Nov-Feb. Annual rainfall 25-30+ inches.',
    eraBreakdown: '40% pre-1930, 20% 1930-1950, 20% 1950-1975, 10% 1975-2005, 10% post-2005',
    roofingNote: 'Hills are VHFHSZ — Class A mandatory, no wood shake. Berkeley has notoriously thorough plan review (3-6 week permits). Standing seam metal gaining popularity on hillside homes. 80+ designated historic landmarks may require Design Review for visible roof changes.',
    sidingNote: 'Brown Shingle style is locally sacred — Landmark Preservation Commission actively reviews alterations. Original redwood shingles must often be replaced in kind on designated landmarks. Hardie Shingle profiles popular as durable alternative on non-designated homes.',
    windowNote: 'Measure G energy ordinance imposes requirements beyond Title 24. Historic homes may need wood-profiled replacements. BART noise along Shattuck corridor drives acoustic glazing demand.',
  },
  {
    city: 'Fremont',
    county: 'Alameda',
    state: 'CA',
    slug: 'fremont',
    countySlug: 'alameda',
    neighborhoods: [
      'Niles',
      'Mission San Jose',
      'Irvington',
      'Warm Springs',
      'Centerville',
      'Glenmoor',
      'Sundale',
      'Parkmont',
    ],
    medianHomePrice: '$1,500,000',
    population: '230,504',
    keyFeature: 'home to Tesla\'s Fremont Factory and top-rated schools',
    homeStyles: '1950s-60s ranch homes in Centerville and Niles, 1970s-80s tract homes in Mission San Jose, large 1990s-2000s executive homes in Mission Hills, and 2010s+ townhomes near Warm Springs BART',
    climateFactor: 'significantly warmer and drier than coastal Bay Area — summer highs 85-95°F, minimal fog, strong UV exposure, and Diablo wind fire risk in eastern hills near Mission Peak',
    commonIssue: 'UV-driven shingle granule loss and curling 5-10 years earlier than foggy areas, T1-11 plywood siding delamination on 1970s-80s tract homes, and stucco hairline cracking from thermal cycling',
    priceTier: 'premium',
    climateZone: 4,
    microclimate: 'Warmest city in Alameda County. Summer highs 85-95°F (vs 65-75°F in Berkeley). Virtually fog-free. Low humidity below 30% in summer. Diablo winds gust 50+ mph through Niles Canyon.',
    eraBreakdown: '5% pre-1940, 15% 1940-1960, 35% 1960-1985, 30% 1985-2010, 15% post-2010',
    roofingNote: 'Eastern hills are VHFHSZ — Class A required. Climate Zone 4 has stricter cool roof requirements than coastal Zone 3. Concrete tile common on 1990s-2000s Mediterranean-style homes. City permits are efficient — 1-2 week turnaround.',
    sidingNote: 'Stucco dominant on 60%+ of homes. T1-11 plywood on budget 1970s-80s tracts frequently replaced with fiber cement. No historic preservation requirements outside tiny Niles district. EIFS moisture problems on some 1990s-2000s homes.',
    windowNote: 'Climate Zone 4 has stricter solar heat gain requirements than coastal cities. Dual-pane Low-E standard. Noise from I-880 and BART drives acoustic glazing near stations. Many HOAs specify window style and color.',
  },
  {
    city: 'Hayward',
    county: 'Alameda',
    state: 'CA',
    slug: 'hayward',
    countySlug: 'alameda',
    neighborhoods: [
      'Hayward Hills',
      'Downtown Hayward',
      'South Hayward',
      'Cherryland',
      'Fairview',
      'Harder-Tennyson',
      'Mission Hills',
    ],
    medianHomePrice: '$880,000',
    population: '162,954',
    keyFeature: 'gateway to the East Bay hills with Cal State University East Bay',
    homeStyles: '1940s-50s modest ranch homes near downtown, 1960s-70s stucco tract homes and duplexes throughout central Hayward, and 1980s-90s larger homes in Hayward Hills east of Mission Blvd',
    climateFactor: 'transition zone between foggy bayside and warm inland — the Hayward Fault runs directly through the city along Mission Blvd, creating the defining seismic hazard plus fire risk in eastern hills',
    commonIssue: 'Hayward Fault settlement causing cracked stucco and misaligned doors/windows, cheap 1960s-70s construction with poor weather barriers leading to moisture intrusion, and T1-11 siding failure on budget tract homes',
    priceTier: 'mid',
    climateZone: 3,
    microclimate: 'Western bayside: morning fog, 60-75°F, salt air. Central: 70-82°F. Eastern hills: 75-90°F, fire-prone. The fault scarp creates a temperature boundary — east of Mission Blvd averages 5-8°F warmer.',
    eraBreakdown: '10% pre-1940, 20% 1940-1960, 35% 1960-1985, 25% 1985-2010, 10% post-2010',
    roofingNote: 'Eastern hills are VHFHSZ — Class A required. Flat roofs common on 1960s-70s duplexes with chronic ponding. The Hayward Fault proximity means structural roof changes may trigger seismic upgrade requirements. Quick permits: 1-2 weeks.',
    sidingNote: 'Stucco over wood frame is overwhelming majority (1960s-80s). Many have stucco directly over building paper with no rain screen. T1-11 plywood rotting at bottom edges from splash-back. Industrial fallout near I-880 accelerates paint degradation.',
    windowNote: 'Aluminum single-pane still prevalent on 1960s-70s homes — biggest energy upgrade available. BART noise at South Hayward and Hayward stations drives acoustic glazing. Egress compliance issues common in older bedrooms.',
  },
  {
    city: 'San Leandro',
    county: 'Alameda',
    state: 'CA',
    slug: 'san-leandro',
    countySlug: 'alameda',
    neighborhoods: [
      'Estudillo Estates',
      'Bay-O-Vista',
      'Washington Manor',
      'Marina',
      'Broadmoor',
      'Downtown San Leandro',
      'Floresta Gardens',
    ],
    medianHomePrice: '$900,000',
    population: '91,361',
    keyFeature: 'waterfront living along the San Francisco Bay with easy BART access',
    homeStyles: '1920s-40s Craftsman and Spanish Colonial Revival in Estudillo Estates, 1940s-50s postwar ranch homes (dominant citywide), and 2000s+ mixed-use near San Leandro BART',
    climateFactor: 'moderate bayside climate — morning fog in Marina district, salt air west of I-880, notably cooler than Fremont (10-15°F difference on summer afternoons), and minimal fire risk due to flat terrain',
    commonIssue: 'the 1940s-50s housing stock is 75-85 years old with original siding, roofing, and windows reaching end-of-life simultaneously. Asbestos siding shingles (1950s) still on many homes requiring abatement. Termite damage widespread.',
    priceTier: 'mid',
    climateZone: 3,
    microclimate: 'Uniformly moderate and flat. Marina district: foggier, 62-72°F summers, salt air. Central/east: 68-80°F. Notably cooler than Fremont but warmer than SF by 5-8°F. Low wildfire risk.',
    eraBreakdown: '15% pre-1940, 35% 1940-1960, 25% 1960-1985, 15% 1985-2010, 10% post-2010',
    roofingNote: 'No VHFHSZ — standard materials permitted everywhere. 90%+ composition shingles. Many 1940s-50s homes re-roofed 2-3 times with layers — tear-off required when exceeding 2 layers. Efficient permitting: 1-2 weeks.',
    sidingNote: 'Original wood clapboard on 1920s-50s homes is the largest re-siding market. Asbestos cement shingles still present on hundreds of homes — abatement adds $5K-$15K. Estudillo Estates historic district requires architectural review for contributing structures.',
    windowNote: 'Most 1940s-50s homes still have original wood-frame single-pane or early aluminum sliders — huge replacement market. BART noise near Bayfair/San Leandro stations drives acoustic glazing. Egress sizing issues in 1940s-50s cottage bedrooms.',
  },

  // ── Contra Costa County ───────────────────────────────────────────────
  {
    city: 'Antioch',
    county: 'Contra Costa',
    state: 'CA',
    slug: 'antioch',
    countySlug: 'contra-costa',
    neighborhoods: [
      'Lone Tree',
      'Deer Valley',
      'Black Diamond',
      'Sycamore',
      'Prewett Ranch',
      'Sand Creek',
      'Downtown Antioch',
    ],
    medianHomePrice: '$620,000',
    population: '115,291',
    keyFeature: 'fastest-growing East Bay city on the San Joaquin River Delta',
    homeStyles: '1970s-80s ranch-style tract homes in older neighborhoods, 2000s-2020s two-story stucco production homes in Lone Tree, Sand Creek, and Deer Valley, and some Victorian-era homes in Rivertown historic district',
    climateFactor: 'one of the hottest cities in Contra Costa — summer highs routinely 95-105°F with Delta winds and Diablo wind events, low humidity often under 20%',
    commonIssue: 'premature shingle granule loss and curling from extreme heat cycling (40°F nights to 100°F+ days), stucco cracking on post-2000 production homes, and faded paint within 5-7 years from intense UV',
    priceTier: 'budget',
    climateZone: 12,
    microclimate: 'Summer highs average 93°F with 20+ days over 100°F. Delta breeze provides evening cooling. Diablo winds gust 40-60 mph in fall. Annual rainfall ~13 inches — driest of the CCC cities.',
    eraBreakdown: '8% pre-1960, 22% 1960-1979, 25% 1980-1999, 35% 2000-2015, 10% post-2016',
    roofingNote: 'Climate Zone 12 cool roof requirements apply — min aged solar reflectance 0.20 steep-slope. Standard 3-tab shingles degrade faster here (15-18 year life vs 20-25 coastal). Concrete tile gaining popularity for heat resilience. No widespread WUI designation in city core.',
    sidingNote: 'Post-2000 homes almost entirely stucco. Thermal cycling causes hairline cracking at window corners. South/west stucco needs recoating every 8-10 years. Older ranch homes have T1-11 or asbestos-containing siding from 1970s.',
    windowNote: 'Dual-pane low-E essential given summer cooling loads. Many pre-2000 homes still have single-pane aluminum. West-facing windows are the biggest energy penalty. Vinyl frames most common at this price point.',
  },
  {
    city: 'Concord',
    county: 'Contra Costa',
    state: 'CA',
    slug: 'concord',
    countySlug: 'contra-costa',
    neighborhoods: [
      'Dana Estates',
      'Lime Ridge',
      'Pine Hollow',
      'Four Corners',
      'Holbrook',
      'Ellis Lake',
      'Todos Santos',
      'Cowell',
    ],
    medianHomePrice: '$750,000',
    population: '129,295',
    keyFeature: 'central Contra Costa hub home to the Concord Pavilion and Todos Santos Plaza',
    homeStyles: '1960s-80s single-story ranch and split-level homes in Dana Estates, Holbrook, and Ellis Lake, 1980s-90s two-story California Contemporary in Pine Hollow and Lime Ridge, and some 1940s-50s cottages near Todos Santos',
    climateFactor: 'inland heat corridor with summer highs regularly 90-100°F, Diablo winds funnel through Ygnacio Valley corridor with gusts to 70 mph, and low humidity 15-25%',
    commonIssue: 'aging 1960s-70s roofing stock on second or third roof, original wood shake needing fire-safe conversion, stucco delamination from 40+ years of thermal cycling, and dry rot at eaves from irrigation overspray combined with hot sun',
    priceTier: 'mid',
    climateZone: 12,
    microclimate: 'Summer average high 91°F with 10-15 days above 100°F. Ygnacio Valley acts as wind funnel during Diablo events. Valley floor retains heat — urban heat island adds 3-5°F. Morning fog is rare.',
    eraBreakdown: '5% pre-1950, 30% 1950-1969, 35% 1970-1989, 20% 1990-2009, 10% post-2010',
    roofingNote: 'Large stock of 1960s-70s homes with low-slope sections (under 2:12) requiring modified bitumen or TPO. Wood shake conversions to Class A a priority. GAF Timberline HDZ and Owens Corning Duration most-specified architecturals.',
    sidingNote: 'Mixed stock: T1-11 plywood, hardboard (Masonite), and wood lap on older homes. Hardboard from 1970s-80s has swelled from moisture at failed caulk. Fiber cement the standard replacement. South-facing stucco fades within 5-8 years.',
    windowNote: 'Massive upgrade opportunity — thousands of homes still have original single-pane aluminum. Milgard and Anlin most popular brands. Low-SHGC glass (0.25 or lower) critical for west/south to manage cooling.',
  },
  {
    city: 'Richmond',
    county: 'Contra Costa',
    state: 'CA',
    slug: 'richmond',
    countySlug: 'contra-costa',
    neighborhoods: [
      'Point Richmond',
      'Marina Bay',
      'El Cerrito Hills',
      'Hilltop',
      'Iron Triangle',
      'Atchison Village',
      'East Richmond Heights',
    ],
    medianHomePrice: '$650,000',
    population: '116,448',
    keyFeature: 'waterfront city with Rosie the Riveter National Park and Bay Trail access',
    homeStyles: 'WWII-era worker housing (1940s cottages, Atchison Village), early-1900s Victorians and Craftsmans in Point Richmond, 1960s-70s suburban ranch in Hilltop, and 1990s-2000s contemporary condos in Marina Bay',
    climateFactor: 'the outlier in Contra Costa — marine-influenced climate (Climate Zone 5, not 12). Summer highs only 72-85°F. Salt air corrosion on waterfront. Strong prevailing westerlies from the Golden Gate. Fog 50-80 days/year.',
    commonIssue: 'salt air corrosion on metal flashings, gutters, and fasteners near waterfront. WWII-era homes have lead paint and asbestos siding requiring hazmat-aware work. Wind-driven rain penetration on exposed hillside homes. Dry rot from persistent marine moisture.',
    priceTier: 'budget',
    climateZone: 5,
    microclimate: 'Significantly cooler than inland CCC (72°F avg summer high vs 91°F+ inland). Westerly winds average 10-15 mph with 30+ mph gusts. Marine fog 50-80 days/year. Annual rainfall ~23 inches — wettest of the five CCC cities.',
    eraBreakdown: '15% pre-1940, 40% 1940-1959, 20% 1960-1979, 15% 1980-1999, 10% post-2000',
    roofingNote: 'Climate Zone 5 (marine) — different energy requirements than inland CCC cities. Less cool roof focus, more wind resistance. Impact-resistant shingles smart for wind exposure. Point Richmond hillside homes need specialized installation for steep lots.',
    sidingNote: 'Diverse stock: wood lap on pre-war, asbestos-cement on 1940s-50s cottages requiring abatement, stucco on 1960s-70s. Salt air means paint lasts only 5-7 years on Bay-facing facades. Hardie ColorPlus factory finish ideal for corrosion resistance.',
    windowNote: 'Marine environment makes material selection critical — uncoated aluminum corrodes. Vinyl or fiberglass preferred. Fog means solar heat gain is less of an issue than inland. Sound-rated windows popular near BNSF rail corridor.',
  },
  {
    city: 'San Ramon',
    county: 'Contra Costa',
    state: 'CA',
    slug: 'san-ramon',
    countySlug: 'contra-costa',
    neighborhoods: [
      'Dougherty Valley',
      'Gale Ranch',
      'Canyon Lakes',
      'Windemere',
      'Westside',
      'Twin Creeks',
      'Old Ranch',
    ],
    medianHomePrice: '$1,600,000',
    population: '84,605',
    keyFeature: 'headquarters to Chevron and home to top-rated San Ramon Valley schools',
    homeStyles: '2000-2015 two-story stucco Mediterranean and California Contemporary in Dougherty Valley and Gale Ranch (2,000-4,000 sqft), 1980s-90s homes around Canyon Lakes, and 1970s-80s ranch in Windemere and Old Ranch',
    climateFactor: 'hot inland valley between East Bay Hills and Mt. Diablo — summer highs 90-100°F. Diablo winds funnel down the valley with gusts to 70 mph and single-digit humidity creating extreme fire conditions. Significant WUI fire risk on hillside edges.',
    commonIssue: 'first-generation roof replacements on massive 2000-2010 housing stock hitting 15-25 year mark. Builder-grade materials have shorter lifespan under intense heat. Stucco cracking at 15-20 year mark on Dougherty Valley homes. HOA approvals required for all exterior work.',
    priceTier: 'premium',
    climateZone: 12,
    microclimate: 'Summer average 92°F with 10-15 days above 100°F. Valley thermal bowl — Delta breeze arrives later here (7-8 PM). Morning frost possible Nov-Feb. Diablo wind events bring sustained 30-50 mph winds with single-digit humidity.',
    eraBreakdown: '5% pre-1970, 20% 1970-1989, 25% 1990-2004, 40% 2005-2015, 10% post-2016',
    roofingNote: 'WUI fire zone on western and eastern hillsides — Class A mandatory. Large HOA presence requires material and color approval before city permits. Concrete/clay tile common on Mediterranean homes — often need underlayment replacement at 20-25 years. Cool roof coatings popular for flat-tile roofs.',
    sidingNote: 'Predominantly stucco (90%+). Two-story production homes develop cracking at expansion joints, window surrounds, and floor-line transitions. Elastomeric recoating is standard maintenance. HOAs regulate colors — warm earth tones and grays dominate.',
    windowNote: 'Most homes have original dual-pane vinyl from construction, but early 2000s units reaching end of seal life (fogging). Low SHGC glass (0.22-0.25) critical on west/south. Fiberglass frames (Marvin, Pella) popular in this premium market. HOA approval typically required for frame color.',
  },
  {
    city: 'Walnut Creek',
    county: 'Contra Costa',
    state: 'CA',
    slug: 'walnut-creek',
    countySlug: 'contra-costa',
    neighborhoods: [
      'Northgate',
      'Rossmoor',
      'Saranap',
      'Parkmead',
      'Lakewood',
      'Alamo Creek',
      'Downtown Walnut Creek',
      'Indian Valley',
    ],
    medianHomePrice: '$1,200,000',
    population: '71,903',
    keyFeature: 'upscale shopping and dining hub with Mt. Diablo trailhead access',
    homeStyles: '1950s-60s California ranch homes on larger lots in Parkmead and Lakewood, Rossmoor 55+ community (~9,000 units of 1960s-80s condos/co-ops), 1970s-80s two-story tracts in Northgate, and newer 1990s-2000s homes in Indian Valley',
    climateFactor: 'inland with summer highs 90-100°F and periodic 105°F+ heat waves. Mt. Diablo creates downslope warming during Diablo wind events. WUI fire zones along western ridge and Shell Ridge. Low summer humidity 15-25%.',
    commonIssue: 'Rossmoor\'s massive aging stock (original 1960s-80s materials reaching end-of-life en masse) creates high demand. Original wood shake roofs on 1960s-70s ranch homes need fire-safe conversion. Stucco cracking from 40+ years of thermal cycling.',
    priceTier: 'premium',
    climateZone: 12,
    microclimate: 'Summer average 90°F, slightly cooler than San Ramon due to Ygnacio Valley corridor bringing Delta breeze earlier. Winter low 40°F. Convergence of three valleys creates variable wind patterns. Diablo winds hit hard from Shell Ridge gap.',
    eraBreakdown: '5% pre-1950, 30% 1950-1969, 35% 1970-1989, 20% 1990-2009, 10% post-2010',
    roofingNote: 'WUI fire zones on Acalanes Ridge and near Shell Ridge — Class A required. Rossmoor has its own architectural review board with specific approved materials. Many older homes still have original wood shake. Premium market supports synthetic slate and standing-seam metal.',
    sidingNote: '1950s-60s ranch homes have wood lap or board-and-batten. Rossmoor has T1-11 needing replacement. Premium market supports Hardie Artisan profiles. West-facing walls take worst UV — fading and chalking are primary complaints.',
    windowNote: 'Rossmoor residents are a major replacement market — upgrading single-pane aluminum to dual-pane. Premium market supports Marvin and Andersen. Picture windows popular for Mt. Diablo views. Sound-rated windows in demand near I-680.',
  },

  // ── Marin County ──────────────────────────────────────────────────────
  {
    city: 'Larkspur',
    county: 'Marin',
    state: 'CA',
    slug: 'larkspur',
    countySlug: 'marin',
    neighborhoods: [
      'Greenbrae',
      'Bon Air',
      'Baltimore Park',
      'Murray Park',
      'Hillview',
      'Downtown Larkspur',
    ],
    medianHomePrice: '$1,800,000',
    population: '13,014',
    keyFeature: 'charming creek-side town with the Larkspur Ferry to San Francisco',
    homeStyles: '1950s-60s California ranch homes in Greenbrae, postwar subdivisions in Bon Air and Murray Park, and some 1920s-30s Craftsman cottages in Baltimore Park',
    climateFactor: 'moderate fog exposure shielded by Corte Madera Ridge, heavy rainfall (~41 inches/year), and fire hazard severity zones requiring Class A roofing',
    commonIssue: 'moisture damage from heavy winter rain on aging postwar roofs, moss and algae on north-facing roofs shaded by mature oaks, and leaf debris clogging gutters causing fascia rot',
    priceTier: 'luxury',
    climateZone: 2,
    microclimate: 'Moderate fog, shielded from direct Pacific exposure. Summer highs low-to-mid 70s°F, cooler than Novato by 5-8°F. Annual rainfall ~41 inches. Wind moderate.',
    eraBreakdown: '8% pre-1940, 20% 1940-1959, 35% 1960-1979, 22% 1980-1999, 9% post-2000',
    roofingNote: 'Fire hazard zones require Class A roofing — wood shake prohibited. Heavy rainfall demands premium underlayment and flashing. Moss accumulation common on shaded slopes; zinc strip installation recommended. Many 1950s-60s roofs on second or third replacement.',
    sidingNote: 'Historic downtown has design review for visible exterior changes. Fiber cement increasingly popular as replacement for aging redwood siding. Natural wood finishes preferred to maintain Marin organic aesthetic.',
    windowNote: 'Fog condensation moderate. View preservation less critical than hillside cities. Many homeowners upgrading 1960s single-pane aluminum near Highway 101 for noise reduction.',
  },
  {
    city: 'Mill Valley',
    county: 'Marin',
    state: 'CA',
    slug: 'mill-valley',
    countySlug: 'marin',
    neighborhoods: [
      'Tamalpais Valley',
      'Strawberry',
      'Alto',
      'Homestead Valley',
      'Blithedale Canyon',
      'Scott Highlands',
      'Downtown Mill Valley',
    ],
    medianHomePrice: '$2,100,000',
    population: '14,854',
    keyFeature: 'nestled at the base of Mt. Tamalpais with world-class hiking and redwoods',
    homeStyles: 'early 1900s brown-shingle Craftsman cottages near downtown, 1950s-70s mid-century modern on hillsides (post-and-beam, walls of glass), and contemporary hillside builds on stilts in Tamalpais Valley and Homestead Valley',
    climateFactor: 'heavy fog exposure directly in the Golden Gate fog belt, persistent marine moisture under redwood canopy, annual rainfall 41-50+ inches, and high fire risk throughout',
    commonIssue: 'moss, algae, and lichen growth on roofs is the defining problem — persistent fog + shade creates ideal conditions. Wood rot on Craftsman and mid-century homes in fog-exposed canyons. Hillside drainage causing foundation movement.',
    priceTier: 'luxury',
    climateZone: 2,
    microclimate: 'Heavy fog May-September, burns off by mid-morning but returns late afternoon. Summer highs mid-60s to low-70s°F in fog belt, up to 80°F on sunny hillsides. Canyon bottoms are cooler/wetter than ridgetops. 41-50+ inches rainfall.',
    eraBreakdown: '27% pre-1940, 25% 1940-1959, 28% 1960-1979, 12% 1980-1999, 8% post-2000',
    roofingNote: 'Class A fire-rated mandatory — wood shake prohibited. Steep-slope roofing common (many roofs exceed 6:12 pitch). Moss accumulation is severe — zinc/copper strips standard. Professional cleaning needed every 2-3 years. Composite shake (DaVinci, CeDUR) popular as fire-compliant wood look.',
    sidingNote: 'Redwood siding is signature Mill Valley but requires restaining every 5-7 years minimum in the fog belt. Fiber cement (HardieShingle) gaining popularity for rot resistance. Design Review Board evaluates exterior changes. Heritage tree protection restricts scaffold access.',
    windowNote: 'Fog condensation is significant — causes sill rot and mold on single-pane windows. Dual-pane with warm-edge spacers essential. Marine-grade hardware recommended. Mid-century homes have floor-to-ceiling glass requiring careful replacement to preserve character.',
  },
  {
    city: 'Novato',
    county: 'Marin',
    state: 'CA',
    slug: 'novato',
    countySlug: 'marin',
    neighborhoods: [
      'Hamilton',
      'Ignacio',
      'Loma Verde',
      'Bel Marin Keys',
      'Indian Valley',
      'Pacheco Valle',
      'Downtown Novato',
    ],
    medianHomePrice: '$1,200,000',
    population: '56,116',
    keyFeature: 'northernmost Marin city with spacious lots and rolling hillside neighborhoods',
    homeStyles: 'Hamilton Field Spanish Colonial Revival (1930s military housing), 1950s Cliff May-designed mid-century modern, 1960s-70s compact ranches in central Novato, and 1970s-80s suburban tracts in San Marin with hillside views',
    climateFactor: 'warmest and driest of the Marin cities — past the fog belt with summer highs reaching low-to-mid 80s°F, more UV exposure than coastal Marin, and moderate fire risk on western hillsides',
    commonIssue: 'sun damage and heat cycling on asphalt shingles — faster granule loss than foggy southern Marin. 1970s-80s tract homes at the 30-40 year replacement window with original builder-grade materials.',
    priceTier: 'premium',
    climateZone: 2,
    microclimate: 'Warmest Marin city. Summer highs ~80°F. Minimal fog — 5-8 miles too far inland for marine layer. Greater diurnal range than coastal cities. Annual rainfall 25-35 inches. Occasional Diablo winds in fall.',
    eraBreakdown: '5% pre-1940, 10% 1940-1959, 45% 1960-1979, 29% 1980-1999, 11% post-2000',
    roofingNote: 'WUI fire code requires fire-rated materials on western hillside properties. Heat cycling is more of a concern than moisture. Hamilton Field historic Mission tile roofs require specialized preservation. Cool/reflective roofing popular for summer heat.',
    sidingNote: 'Less redwood siding than southern Marin — stucco and wood-composite common on 1970s-80s tracts. Hamilton Field Spanish Colonial stucco is historically protected. Sun-fading of painted surfaces more common than in foggy Mill Valley.',
    windowNote: 'Less fog condensation but higher solar heat gain than southern Marin — SHGC matters more here. Hillside homes in Indian Valley benefit from view-optimized glazing. Many 1970s-80s homes still have single-pane aluminum.',
  },
  {
    city: 'San Rafael',
    county: 'Marin',
    state: 'CA',
    slug: 'san-rafael',
    countySlug: 'marin',
    neighborhoods: [
      'Dominican',
      'Gerstle Park',
      'Sun Valley',
      'Peacock Gap',
      'Terra Linda',
      'Lucas Valley',
      'Downtown San Rafael',
      'Canal District',
    ],
    medianHomePrice: '$1,300,000',
    population: '62,022',
    keyFeature: 'Marin County seat and home to the Frank Lloyd Wright-designed Marin Civic Center',
    homeStyles: 'Victorian-era homes (1880s-1910s) in Gerstle Park and Dominican, ~1,500 post-and-beam ranches and 400 Kenney Homes in Terra Linda, mid-century Lucas Valley homes, and 1970s-80s golf course homes in Peacock Gap',
    climateFactor: 'noticeably warmer and less foggy than Mill Valley — can be 15°F higher than Sausalito. Moderate fire risk on hillside neighborhoods (Sun Valley, Lucas Valley). Canal District is a low-lying flood zone.',
    commonIssue: 'wide range due to housing diversity: Victorian homes need foundation attention alongside roofing, mid-century flat roofs in Terra Linda/Lucas Valley prone to ponding, and aging 1960s shingle roofs past typical lifespan citywide',
    priceTier: 'premium',
    climateZone: 2,
    microclimate: 'Summer highs upper-70s°F. Minimal fog — 10+ miles inland. More sun exposure than Mill Valley/Larkspur. East-facing Lucas Valley hillsides 5-10°F warmer in summer. Annual rainfall ~30 inches.',
    eraBreakdown: '10% pre-1940, 25% 1940-1959, 30% 1960-1979, 22% 1980-1999, 7% post-2000',
    roofingNote: 'Hillside Overlay District requires Environmental and Design Review for roofing changes that increase height on 25%+ slopes. Class A required in WUI zones. Flat-roof mid-century homes (Terra Linda, Lucas Valley) need specialized membrane systems. Steep hillside properties require specialized access.',
    sidingNote: 'Victorian homes in Gerstle Park feature original wood clapboard needing careful restoration. Terra Linda has board-and-batten or T1-11 — fiber cement is a common upgrade. Environmental Design Review applies to additions over 500 sqft.',
    windowNote: 'Less fog than Mill Valley — moderate marine influence. View preservation important for hillside homes. Frank Lloyd Wright Civic Center established appreciation for integrated glass design. Terra Linda mid-century homes have original clerestory windows defining the architecture.',
  },

  // ── Napa County ───────────────────────────────────────────────────────
  {
    city: 'Napa',
    county: 'Napa',
    state: 'CA',
    slug: 'napa',
    countySlug: 'napa',
    neighborhoods: [
      'Browns Valley',
      'Old Town Napa',
      'Westwood',
      'Bel Aire',
      'Silverado',
      'Alta Heights',
      'Oxbow District',
    ],
    medianHomePrice: '$850,000',
    population: '79,657',
    keyFeature: 'heart of Napa Valley wine country with a revitalized downtown riverfront',
    homeStyles: 'late 1800s Victorians and Queen Annes in Old Town, 1950s-60s ranch homes in Browns Valley and Westwood, Mediterranean and Craftsman Revival in Bel Aire, and modern vineyard estates along the Silverado Trail',
    climateFactor: 'hot inland valley with summers regularly exceeding 95-100°F, extreme thermal cycling (30°F winter nights to 100°F+ days), and direct Diablo wind-driven wildfire exposure — the Atlas Fire (2017) destroyed 783 structures',
    commonIssue: 'heat-cracked stucco on south-facing walls, aging wood siding rot on pre-1940 Old Town Victorians, smoke/ash residue staining from repeat wildfire seasons, and premature shingle failure from thermal cycling',
    priceTier: 'mid',
    climateZone: 2,
    microclimate: 'Valley floor with temperature inversions trapping cold air in winter (frost) and heat in summer. Silverado area gets more wind and wildfire risk. Old Town along the Napa River gets fog pooling in winter mornings.',
    eraBreakdown: '10% pre-1920, 15% 1920-1950, 40% 1950-1980, 20% 1980-2000, 15% post-2000',
    roofingNote: 'Class A fire-rated materials required in expanding WUI zones east and north of the city. Ember-resistant vents and non-combustible fascia required. Insurance non-renewals are severe — Class A roof upgrades help get back into standard market. Cool roof options popular for 95°F+ heat.',
    sidingNote: 'Non-combustible siding required in WUI zones — fiber cement dominant. Old Town Victorians require careful material matching. Smoke residue from 2017/2020 fires accelerated paint degradation on wood siding throughout the city.',
    windowNote: 'Tempered glass required in WUI fire zones. West-facing windows need very low SHGC for brutal afternoon sun. Many 1950s-60s ranch homes still have single-pane aluminum — major energy liability in this heat.',
  },
  {
    city: 'American Canyon',
    county: 'Napa',
    state: 'CA',
    slug: 'american-canyon',
    countySlug: 'napa',
    neighborhoods: [
      'Canyon Oaks',
      'Town Center',
      'Napa Junction',
      'Elliot Ranch',
      'Green Island',
    ],
    medianHomePrice: '$720,000',
    population: '24,436',
    keyFeature: 'gateway to Napa Valley with the wetlands of the American Canyon Preserve',
    homeStyles: '1990s-2000s suburban tract homes with stucco and tile roofs, newer two-story New Traditional and contemporary farmhouse in Watson Ranch, and scattered 1970s-80s ranch homes west of Highway 29',
    climateFactor: 'transitional climate between cooler Bay wind corridor and hot Napa Valley interior — moderate summers (mid-80s to low 90s), wind exposure from Carquinez Strait gap, and lower wildfire risk than upper valley cities',
    commonIssue: 'builder-grade stucco cracking on 1990s-2000s tract homes reaching their 25-30 year maintenance window, faded paint from UV, and original composition roofs from the development boom now at end-of-life',
    priceTier: 'budget',
    climateZone: 2,
    microclimate: 'Cooler than upper Napa Valley by 5-10°F due to marine influence through Carquinez Strait. Windier than cities further up-valley. Less frost than the valley floor. Wind-driven rain is the primary weather challenge.',
    eraBreakdown: '5% pre-1970, 15% 1970-1990, 55% 1990-2010, 25% post-2010',
    roofingNote: 'Most homes built after 1990 with 25-30 year shingles now approaching replacement. Less WUI exposure than northern Napa. Watson Ranch new construction meets current Title 24. Builder-grade roofing often minimum spec — upgrading to architectural shingles or cool roofing makes sense.',
    sidingNote: 'Predominantly stucco from tract home era. Hairline cracking, water intrusion at window flashing, and paint chalking from UV are common. Wine country aesthetic pressure is lower here — more suburban/practical character.',
    windowNote: 'Most 1990s homes have dual-pane vinyl approaching seal failure point (foggy glass). West-facing windows along Highway 29 get significant afternoon heat gain. Vinyl frames on darker stucco homes can warp in direct summer sun.',
  },
  {
    city: 'St. Helena',
    county: 'Napa',
    state: 'CA',
    slug: 'st-helena',
    countySlug: 'napa',
    neighborhoods: [
      'Downtown St. Helena',
      'Spring Mountain',
      'Meadowood',
      'Pope Valley',
      'Sulphur Springs',
    ],
    medianHomePrice: '$2,500,000',
    population: '6,070',
    keyFeature: 'iconic Napa Valley main street town surrounded by world-renowned vineyards',
    homeStyles: '1870s-1910s Victorians (Queen Anne, Italianate) lining tree-shaded streets, Craftsman bungalows from the 1910s-30s, mid-century ranch on larger lots toward Spring Mountain, and contemporary luxury vineyard estates in Meadowood',
    climateFactor: 'most extreme heat in the county — summers regularly 100-110°F. Glass Fire (2020) devastated eastern hills, destroying Meadowood Resort. Significant frost risk as cold air pools on the narrow valley floor. Intense year-round UV.',
    commonIssue: 'fire damage restoration in Glass Fire burn zone (eastern hills), aging wood trim and siding on 1880s-1920s historic homes, heat stress on south-facing stucco, and wildfire smoke/ash residue embedded in porous surfaces',
    priceTier: 'luxury',
    climateZone: 4,
    microclimate: 'Narrow valley floor creates extreme temperature amplification — Mayacamas and Vaca ranges trap heat, producing 105-110°F summer peaks. Severe winter frost pockets. Eastern hillside faces highest fire risk from Diablo winds.',
    eraBreakdown: '20% pre-1900, 25% 1900-1940, 20% 1940-1970, 20% 1970-2000, 15% post-2000',
    roofingNote: 'Class A fire-rated mandatory in extensive WUI zones. Post-Glass Fire rebuilds require full Chapter 7A. Insurance extremely difficult for hillside properties — many on FAIR Plan. Premium materials expected: standing seam metal, composite slate, concrete tile. Historic downtown may require design review.',
    sidingNote: 'Historic Preservation Overlay restricts exterior alterations downtown. Residential historic homes require period-appropriate siding profiles. Non-combustible siding required in WUI zones. Hardie Artisan popular for matching historic wood with fire compliance.',
    windowNote: 'Tempered glass required in all WUI properties. Very low SHGC essential for extreme heat — west-facing windows get punishing afternoon sun reflected off hillsides. Historic homes need sympathetic replacement profiles.',
  },
  {
    city: 'Calistoga',
    county: 'Napa',
    state: 'CA',
    slug: 'calistoga',
    countySlug: 'napa',
    neighborhoods: [
      'Downtown Calistoga',
      'Silverado Trail',
      'Knights Valley',
      'Diamond Mountain',
    ],
    medianHomePrice: '$1,200,000',
    population: '5,770',
    keyFeature: 'hot springs resort town at the northern tip of Napa Valley',
    homeStyles: '19th-century resort town cottages from the 1860s-80s hot springs era, Victorian homes with wraparound porches, 1920s-50s ranch and bungalows, and contemporary luxury vineyard estates on Diamond Mountain',
    climateFactor: 'hottest city in Napa Valley — summers routinely exceed 105°F at the narrow valley tip. Tubbs Fire (2017) originated here, forcing full-town evacuation. Geothermal activity creates unique soil and mineral conditions.',
    commonIssue: 'post-Tubbs Fire restoration, mineral deposit staining from geothermal groundwater, extreme UV and heat damage to south-facing surfaces, and wildfire ember damage to wood-sided structures',
    priceTier: 'premium',
    climateZone: 4,
    microclimate: 'Hottest Napa microclimate — valley narrows to a point between Mt. St. Helena (4,342 ft) and the Palisades, trapping heat. Diablo winds funnel through with amplified force. Geothermal underground heat. Paradoxically high frost risk at valley terminus.',
    eraBreakdown: '15% pre-1900, 25% 1900-1950, 25% 1950-1980, 20% 1980-2010, 15% post-2010',
    roofingNote: 'Class A mandatory — nearly surrounded by wildfire-prone terrain. Insurance non-renewals severe — many on FAIR Plan at 3-4x premiums. Standing seam metal popular for fire resistance and heat reflectivity. Geothermal mineral content can corrode certain metal alloys — galvalume and aluminum recommended.',
    sidingNote: 'Non-combustible siding required in WUI. Historic downtown has 1860s-80s storefronts requiring sensitive material choices. Mineral-rich groundwater causes efflorescence on stucco/masonry. Diamond Mountain estates favor natural stone and Corten steel.',
    windowNote: 'Tempered glass required in WUI zones. Triple-pane increasingly justified given extreme heat. Very low SHGC essential on west and south exposures. Older resort-era cottages have non-standard sizes requiring custom replacements.',
  },
  {
    city: 'Yountville',
    county: 'Napa',
    state: 'CA',
    slug: 'yountville',
    countySlug: 'napa',
    neighborhoods: [
      'Downtown Yountville',
      'Veterans Home',
      'Washington Street',
      'Yount Mill Road',
    ],
    medianHomePrice: '$1,800,000',
    population: '3,004',
    keyFeature: 'Michelin-starred culinary capital of Napa Valley',
    homeStyles: '1920s-50s wine country cottages along Washington Street, updated mid-century ranch, Mediterranean villas behind hedge-lined drives, and modern farmhouse with clean lines — all within a tiny 1.5 square mile footprint',
    climateFactor: 'mid-valley with hot summers (95-100°F) moderated by valley width, Atlas Fire (2017) and Glass Fire (2020) both triggered evacuations, and winter frost along the Napa River valley floor',
    commonIssue: 'maintaining premium exterior finishes on high-value properties in harsh UV/heat, aging wood trim on 1920s-50s cottages requiring restoration-quality craftsmanship, and ensuring wildfire resilience for vineyard-adjacent properties',
    priceTier: 'luxury',
    climateZone: 4,
    microclimate: 'Mid-valley floor at widest point — slightly more air circulation than compressed upper valley. Summer highs 95-100°F. Napa River creates morning fog pooling and frost risk in winter. Vineyards on all sides act as heat sink.',
    eraBreakdown: '10% pre-1900, 25% 1900-1950, 30% 1950-1980, 25% 1980-2010, 10% post-2010',
    roofingNote: 'Premium materials expected on virtually every property. Standing seam metal, concrete tile, composite slate standard. Design review may apply for changes visible from Washington Street. Limited inventory means every property is highly visible — workmanship paramount.',
    sidingNote: 'Wine country aesthetic expectations extremely high. Fiber cement must have premium trim detailing. Natural stone and board-and-batten in earth tones dominate. No vinyl, no cheap stucco. Town design review requires materials visible from main thoroughfares.',
    windowNote: 'Large vineyard-view windows are a defining feature — floor-to-ceiling glass oriented toward Mayacamas or valley floor vineyards. Tempered glass in WUI zones. Historic cottages along Washington Street need character-preserving replacements.',
  },

  // ── Santa Clara County ────────────────────────────────────────────────
  {
    city: 'San Jose',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'san-jose',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Willow Glen',
      'Rose Garden',
      'Almaden Valley',
      'Cambrian',
      'Berryessa',
      'Evergreen',
      'Silver Creek',
      'Blossom Valley',
      'Naglee Park',
      'SoFA District',
    ],
    medianHomePrice: '$1,350,000',
    population: '1,013,240',
    keyFeature: 'capital of Silicon Valley and the largest city in the Bay Area',
    homeStyles: 'Queen Anne Victorians and Craftsman bungalows in Naglee Park and Willow Glen, 1960s-80s tract ranches in Cambrian and Blossom Valley, 1980s-2000s stucco two-story in Evergreen and Silver Creek, and 2010s+ infill near Berryessa BART',
    climateFactor: 'warmest major city in Bay Area — summer highs 85-95°F with occasional 100°F+. Only 15 inches of rain. Shielded from fog by Santa Cruz Mountains. Seismic risk from Calaveras and San Andreas faults.',
    commonIssue: 'UV degradation of asphalt shingles from heat cycling, T1-11 plywood siding delamination on 1970s-80s tracts, and expansive clay soils in south San Jose causing foundation movement and stucco cracking',
    priceTier: 'premium',
    climateZone: 4,
    microclimate: 'Downtown/north warmer than south (Almaden gets foothill breeze). East San Jose (Berryessa, Evergreen) is the hottest zone — 5-8°F warmer than Cupertino. Low 30s winter nights with frost near Coyote Creek.',
    eraBreakdown: '10% pre-1940, 20% 1940-1960, 35% 1960-1980, 20% 1980-2000, 15% post-2000',
    roofingNote: 'Title 24 cool roof on low-slope re-roofs. Concrete tile common on 1990s+ homes. Heat cycling is primary cause of premature granule loss. San Jose is California #1 for residential solar — roof+solar bundling standard. City has most streamlined ADU process in Bay Area.',
    sidingNote: 'Stucco dominates post-1970. Willow Glen and Rose Garden have original wood lap needing repainting every 7-10 years or fiber cement replacement. T1-11 on 1970s-80s tract homes in Cambrian/Blossom Valley is prime for Hardie upgrade.',
    windowNote: 'Climate Zone 4 requires U-factor 0.30, SHGC 0.23. Noise from 101/280/680 corridors drives acoustic glazing demand. Older Willow Glen homes have original single-pane wood windows. Dual-pane vinyl is dominant replacement.',
  },
  {
    city: 'Palo Alto',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'palo-alto',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Crescent Park',
      'Old Palo Alto',
      'Professorville',
      'College Terrace',
      'Midtown',
      'Barron Park',
      'Green Acres',
      'Charleston Meadows',
    ],
    medianHomePrice: '$3,500,000',
    population: '68,572',
    keyFeature: 'home to Stanford University and the birthplace of Silicon Valley',
    homeStyles: 'Professorville Historic District has 1890s-1910s Queen Annes and Colonials, 1920s-40s Colonials and Tudors in Old Palo Alto, hundreds of Joseph Eichler mid-century modern homes in Midtown with flat roofs and floor-to-ceiling glass, and 1950s ranches in Barron Park',
    climateFactor: 'moderate compared to inland — summer highs 78-88°F with mild coastal influence. San Andreas Fault 5 miles west. No significant fire risk (flat, urban). Proximity to Bay means slightly higher humidity.',
    commonIssue: 'Eichler homes are THE dominant issue — original tar-and-gravel flat roofs leak, T1-11 siding delaminates, radiant floor heating complicates renovation. Teardown/rebuild activity is intense. Foundation settlement on Bay-side homes from high water table.',
    priceTier: 'luxury',
    climateZone: 4,
    microclimate: '5-8°F cooler than San Jose. North Palo Alto (near Baylands) slightly cooler and more humid. Rarely hits 100°F — maybe 2-3 days/year. Winter lows in high 30s. 15 inches annual rainfall.',
    eraBreakdown: '8% pre-1920, 15% 1920-1940, 45% 1940-1960, 15% 1960-1980, 7% 1980-2000, 10% post-2000',
    roofingNote: 'Eichler flat roofs require specialized membrane systems (TPO, PVC, modified bitumen) — NOT standard shingles. Many Eichler owners switching to white TPO for cool roof compliance. Architectural Review Board may review visible roof changes. Strictest permit process in the county.',
    sidingNote: 'Eichler siding is a niche specialty — original mahogany/redwood vertical board often deteriorated. HardiPanel smooth is the fiber cement replacement. Professorville has wood shingle requiring restoration. Vinyl is considered heresy by the Eichler community.',
    windowNote: 'Eichler floor-to-ceiling glass walls require custom sizing — no stock windows fit. Low-E with low SHGC critical for large glass expanses. Professorville Victorians have bay windows needing custom work. Noise not a major factor in residential neighborhoods.',
  },
  {
    city: 'Mountain View',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'mountain-view',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Old Mountain View',
      'Cuesta Park',
      'Rex Manor',
      'Waverly Park',
      'Gemello',
      'Shoreline West',
      'Sylvan Park',
    ],
    medianHomePrice: '$2,000,000',
    population: '82,376',
    keyFeature: 'home to Google headquarters and NASA Ames Research Center',
    homeStyles: '1910s-40s Craftsman bungalows in Old Mountain View, 1950s-60s ranch homes and some Eichler tracts in Cuesta Park and Rex Manor, 1960s-70s ranches in Waverly Park, and massive new apartment/condo development near Google campus',
    climateFactor: 'Climate Zone 4. Summer highs 80-90°F — slightly cooler than San Jose. North Mountain View gets Bay breeze. Some marine layer influence. 15 inches annual rainfall. San Andreas Fault 8 miles west.',
    commonIssue: '1950s-60s ranch homes with original composition roofs past 25-year life. Eichler homes in Cuesta Park with flat-roof and siding issues. Aging single-pane windows driving high AC bills. North Mountain View near Bay has soil moisture issues.',
    priceTier: 'luxury',
    climateZone: 4,
    microclimate: 'North Mountain View (Shoreline) 3-5°F cooler with Bay breezes. South (near El Camino, bordering Sunnyvale) is warmer. Overall 3-5°F cooler than San Jose, 2-3°F warmer than Palo Alto. Fog rare but marine overcast occasionally reaches north.',
    eraBreakdown: '8% pre-1940, 35% 1940-1960, 30% 1960-1980, 10% 1980-2000, 17% post-2000',
    roofingNote: 'Eichler flat-roof challenges similar to Palo Alto — TPO/PVC replacements common. Conventional ranches use architectural shingles. Google-driven property values justify premium materials. Solar-ready requirements on new builds. ADU-friendly city with pre-approved plans.',
    sidingNote: 'Mix of stucco, wood lap, and T1-11 on mid-century homes. Fiber cement is dominant upgrade. Eichler siding follows Palo Alto patterns. New construction near Google campus uses modern cementitious panels and metal accents.',
    windowNote: 'Mid-century ranch homes have original aluminum single-pane — huge upgrade opportunity. Eichler glass walls need custom solutions. Noise reduction relevant near Highway 101 and Central Expressway. El Camino-adjacent homes benefit from sound-rated windows.',
  },
  {
    city: 'Sunnyvale',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'sunnyvale',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Lakewood Village',
      'Birdland',
      'Ponderosa',
      'Cherry Chase',
      'Raynor Park',
      'Heritage District',
      'De Anza',
    ],
    medianHomePrice: '$1,900,000',
    population: '155,805',
    keyFeature: 'major tech hub home to Apple Park\'s neighbor and Juniper Networks',
    homeStyles: 'Lakewood Village is one of the biggest Eichler concentrations in the Bay Area, 1950s-60s ranch in Birdland (streets named after birds), 1960s-70s tracts in Ponderosa and Cherry Chase, and 1990s-2000s townhomes in northeast Sunnyvale',
    climateFactor: 'Climate Zone 4. Summer highs 82-92°F. Dry Mediterranean with very low humidity. Hayward Fault zone runs through eastern edge. More heat exposure than Peninsula cities.',
    commonIssue: 'Lakewood Village Eichler chronic flat-roof leaks and siding deterioration — the single largest exterior renovation market in Sunnyvale. 1960s-70s tract homes citywide have aging asphalt roofs at end of life. Original aluminum windows are single-pane energy hogs.',
    priceTier: 'luxury',
    climateZone: 4,
    microclimate: 'Northwest (near Moffett Field) 3-5°F cooler with marine influence. South (near Stevens Creek, bordering Cupertino) warmer. East near 101/237 gets heat island from commercial development.',
    eraBreakdown: '5% pre-1940, 30% 1940-1960, 40% 1960-1980, 15% 1980-2000, 10% post-2000',
    roofingNote: 'Lakewood Eichlers require flat-roof membrane systems. Conventional homes predominantly asphalt shingle. Cool roof requirements apply. Hot summers make ridge vent + soffit ventilation critical — without it, attic temps exceed 150°F.',
    sidingNote: 'Lakewood Eichler T1-11 siding is a major replacement market. Stucco dominant on 1970s+ homes. Birdland and Cherry Chase have wood lap benefiting from fiber cement upgrade. HOAs in newer townhome communities mandate stucco or approved fiber cement.',
    windowNote: 'Lakewood Eichlers have signature floor-to-ceiling glass requiring custom replacement. Highway 101/237 noise makes STC-rated windows valuable in northwest Sunnyvale. Lawrence Expressway traffic drives noise demand for adjacent homes.',
  },
  {
    city: 'Cupertino',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'cupertino',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Rancho Rinconada',
      'Monta Vista',
      'Garden Gate',
      'Oak Valley',
      'Seven Springs',
      'Homestead Lanes',
    ],
    medianHomePrice: '$2,800,000',
    population: '60,170',
    keyFeature: 'home to Apple Park and top-ranked Cupertino Union School District',
    homeStyles: 'Rancho Rinconada is a large 1950s-60s Eichler and ranch tract, 1960s-70s ranch and split-level in Monta Vista near foothills, 1970s-80s homes in Garden Gate and Oak Valley, and 1980s-90s two-story in Seven Springs',
    climateFactor: 'Climate Zone 4. Summer highs 82-92°F. Western Cupertino (Monta Vista) gets cooler evenings from mountain downdrafts. 18 inches rainfall (slightly more from foothill orographic effect). Monta Vista Fault runs through western area.',
    commonIssue: 'Rancho Rinconada Eichler flat-roof and siding issues are primary. 1970s-80s homes with original asphalt roofs at end of life. Clay soil in western foothills causes stucco cracking. T1-11 on 1960s-70s homes delaminating.',
    priceTier: 'luxury',
    climateZone: 4,
    microclimate: 'Western Cupertino (Monta Vista, foothills) 3-5°F cooler than eastern, especially at night from cold air drainage. Near Stevens Creek Reservoir — more morning moisture. Eastern (near Apple Park) is warmer, typical valley floor.',
    eraBreakdown: '3% pre-1950, 25% 1950-1960, 45% 1960-1980, 20% 1980-2000, 7% post-2000',
    roofingNote: 'Eichler flat-roof market in Rancho Rinconada mirrors Palo Alto/Sunnyvale. Premium materials justified by ultra-high home values — synthetic slate and standing seam increasingly popular. School-district-driven values make investment easy to justify.',
    sidingNote: 'Rancho Rinconada Eichler siding is a specialty market. Stucco dominant on 1970s-2000s homes. Seven Springs and Oak Valley have HOA-regulated exteriors. Contemporary teardown-rebuilds use mixed stucco + wood accent + cement panel.',
    windowNote: 'School-district-driven values make energy upgrades easy to justify. Rancho Rinconada Eichlers need custom floor-to-ceiling glass. Highway 85 and De Anza Blvd noise drives sound-rated windows. Triple-pane beginning to appear in high-end renovations.',
  },
  {
    city: 'Santa Clara',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'santa-clara',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Old Quad',
      'Washington Square',
      'Rivermark Village',
      'Bowers',
      'Scott Boulevard',
      'Briarwood',
    ],
    medianHomePrice: '$1,700,000',
    population: '127,647',
    keyFeature: 'home to Levi\'s Stadium and Santa Clara University',
    homeStyles: '1900s-30s Craftsman bungalows in the Old Quad near SCU, 1940s-50s small ranch in Washington Square, 1960s-70s tract ranch in Bowers, 2000s Craftsman-influenced townhomes in Rivermark Village, and 2010s+ condos near Levi\'s Stadium',
    climateFactor: 'Climate Zone 4. Summer highs 82-92°F. Valley floor with no coastal influence. Heat island effect from commercial/industrial zones along 101 corridor. No significant fire risk (flat, urban).',
    commonIssue: 'older Old Quad homes near SCU have deferred maintenance on original wood siding. 1960s-70s tracts in Bowers with aging roofs and stucco cracking from thermal cycling. T1-11 deterioration on 1970s homes.',
    priceTier: 'premium',
    climateZone: 4,
    microclimate: 'Relatively uniform climate — flat terrain. Northern Santa Clara marginally cooler with slight Bay influence. Heat island near Great America/Levi\'s Stadium commercial zone.',
    eraBreakdown: '8% pre-1940, 20% 1940-1960, 35% 1960-1980, 17% 1980-2000, 20% post-2000',
    roofingNote: 'Standard asphalt architecturals on most homes. Concrete tile on 1990s+ homes in Rivermark. Industrial zones nearby — particulate accumulation affects roof drainage. Solar very common. Solar-ready design important.',
    sidingNote: 'Stucco dominant post-1970. Old Quad has original wood lap needing replacement. Rivermark has builder-grade stucco and fiber cement. T1-11 on 1970s tracts is primary upgrade target.',
    windowNote: 'Noise from Highway 101, San Tomas Expressway, and Caltrain is significant. Older Washington Square and Old Quad windows are prime replacement candidates. Dual-pane vinyl with Low-E is standard spec.',
  },
  {
    city: 'Saratoga',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'saratoga',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Saratoga Village',
      'Saratoga Woods',
      'Golden Triangle',
      'Quito',
      'Brookglen',
      'Azule',
    ],
    medianHomePrice: '$3,200,000',
    population: '32,020',
    keyFeature: 'exclusive hillside community with top schools and Hakone Gardens',
    homeStyles: '1960s-70s ranch on large lots in Golden Triangle and Quito, 1970s-80s custom hillside homes in Saratoga Woods, and large estates (3,000-6,000 sqft) along Congress Springs Road often Mediterranean or contemporary',
    climateFactor: 'valley floor is 82-92°F summers but hillside homes (above 800ft) are 5-8°F cooler. SIGNIFICANT fire risk — many neighborhoods in VHFHSZ. San Andreas Fault 3-4 miles west. Western foothills get 20-22 inches rainfall vs 15 on valley floor.',
    commonIssue: 'fire hardening is the #1 issue for hillside homes — Class A roofing, ember-resistant vents, fire-resistant siding required. Wood shake removal and replacement is a major market. Complex multi-facet roofs prone to leaks.',
    priceTier: 'luxury',
    climateZone: 4,
    microclimate: 'Most pronounced variation in Santa Clara County. Valley floor (Golden Triangle) similar to Cupertino at 85-92°F. Foothills 5-8°F cooler with evening cold air drainage. Upper hillside 10°F cooler with more moisture, fog, dramatically more rainfall.',
    eraBreakdown: '5% pre-1950, 10% 1950-1960, 50% 1960-1980, 25% 1980-2000, 10% post-2000',
    roofingNote: 'Premium materials exclusively — 50-year architecturals, synthetic slate, standing seam metal. Class A required in VHFHSZ (most hillside properties). Complex rooflines with dormers/valleys require skilled crews. Steep pitches (8:12 to 12:12) need specialized safety equipment.',
    sidingNote: 'Stucco dominant post-1970. Hillside fire zones upgrading to fiber cement with ignition-resistant details. Natural stone and brick accents on luxury builds. No HOAs in most of Saratoga — city has design review for significant changes.',
    windowNote: 'Dual-pane Low-E minimum; many luxury renovations specify triple-pane. Fire-rated windows (tempered, dual-pane) required in VHFHSZ within 30 feet of property line. Large view windows overlooking Silicon Valley are common.',
  },
  {
    city: 'Los Gatos',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'los-gatos',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Downtown Los Gatos',
      'Shannon',
      'Blossom Hill',
      'Monte Sereno',
      'Almond Grove',
      'Los Gatos Meadows',
    ],
    medianHomePrice: '$2,600,000',
    population: '33,529',
    keyFeature: 'charming downtown village at the base of the Santa Cruz Mountains',
    homeStyles: '1880s-1920s Victorians and Craftsman bungalows in historic downtown, 1920s-40s bungalows in Almond Grove, 1950s-60s ranch in Shannon, 1970s-80s tract in Blossom Hill, and custom hillside homes above town in Mediterranean style',
    climateFactor: 'valley floor 82-90°F summers. SIGNIFICANT fire risk in hillside neighborhoods — many in VHFHSZ. San Andreas Fault 3 miles west. Los Gatos Hills 5-10°F cooler with more rainfall (22-28 inches). Heavy oak/redwood canopy above town.',
    commonIssue: 'historic downtown homes with aging slate/shake roofs needing sensitive renovation, fire hardening requirements for hillside homes, tree debris from heavy canopy accumulating on roofs, and 1970s-80s standard aging-roof and T1-11 issues on Blossom Hill tracts',
    priceTier: 'luxury',
    climateZone: 4,
    microclimate: 'Dramatic variation within small area. Downtown warm, sheltered, 85-90°F. Hills above (toward Bear Creek, Hwy 17): 5-10°F cooler, significantly more rainfall, redwood canopy limiting roof sun exposure. Wind channeling through Hwy 17 corridor.',
    eraBreakdown: '8% pre-1920, 12% 1920-1950, 25% 1950-1970, 35% 1970-1990, 20% post-1990',
    roofingNote: 'Historic downtown requires materials compatible with Victorian/Craftsman character — architectural shingles in period colors, synthetic slate. Hillside homes need Class A fire-rated. Wood shake removal market similar to Saratoga. Some downtown homes have original clay tile needing expert restoration.',
    sidingNote: 'Downtown historic homes have original wood lap/shingle — restoration and fiber cement both common depending on Historic Preservation Zone. Hillside homes need ignition-resistant siding. HardiePlank premium upgrade for Shannon and Blossom Hill.',
    windowNote: 'Historic downtown windows (bay, specialty shapes, divided-lite) require custom replacement. Hillside fire zone homes need tempered dual-pane within 30ft of property line. Highway 17 noise relevant for freeway-corridor homes.',
  },
  {
    city: 'Campbell',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'campbell',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Downtown Campbell',
      'Ainsley Park',
      'Hacienda',
      'Campbell Park',
      'San Tomas',
      'White Oaks',
    ],
    medianHomePrice: '$1,650,000',
    population: '43,925',
    keyFeature: 'walkable downtown with the Pruneyard and vibrant farmers market',
    homeStyles: '1910s-30s Craftsman bungalows near downtown Pruneyard, 1950s-60s ranch in Ainsley Park, 1960s-70s ranch and split-level in Hacienda and Campbell Park, and 1970s-80s tracts in San Tomas — much was orchardland until the 1950s-70s housing boom',
    climateFactor: 'Climate Zone 4. Summer highs 83-88°F — moderate. Valley floor, no coastal influence, no elevation change. No fire risk (flat, urban). Uniform climate across the compact city.',
    commonIssue: '1960s-70s ranch homes with original asphalt roofs past 25-year lifespan — the overwhelming exterior issue. T1-11 on 1970s homes delaminating. Single-pane aluminum windows on mid-century homes driving high energy bills.',
    priceTier: 'premium',
    climateZone: 4,
    microclimate: 'Most uniform climate of any city on this list — flat terrain. Slightly cooler than San Jose (3-5°F) from Santa Cruz Mountain foothill proximity. Slightly warmer than Mountain View (3-5°F) from lack of Bay influence.',
    eraBreakdown: '5% pre-1940, 20% 1940-1960, 55% 1960-1980, 12% 1980-2000, 8% post-2000',
    roofingNote: 'Standard asphalt architectural shingles are the sweet spot — moderate price tier means 30-year shingles over premium materials. No fire-zone or hillside complications. Straightforward roofing projects. Good attic ventilation important for summer heat.',
    sidingNote: 'T1-11 to fiber cement upgrade is the biggest siding market. Original wood lap on downtown Craftsmans. Vinyl exists on some budget 1970s homes — upgrade to HardiePlank popular. No significant HOA restrictions in most neighborhoods.',
    windowNote: 'Dual-pane vinyl with Low-E is standard. Noise relevant near Highway 17 (western edge) and Winchester Blvd traffic. Mid-century ranch picture windows are primary replacement targets. Energy-savings payback calculations favorable at this price tier.',
  },
  {
    city: 'Milpitas',
    county: 'Santa Clara',
    state: 'CA',
    slug: 'milpitas',
    countySlug: 'santa-clara',
    neighborhoods: [
      'Calaveras Hills',
      'Augustine',
      'Sunnyhills',
      'Murphy Ranch',
      'Serra Center',
      'Town Center',
    ],
    medianHomePrice: '$1,400,000',
    population: '80,430',
    keyFeature: 'booming tech corridor with the Great Mall and easy 680/880 freeway access',
    homeStyles: '1960s-70s ranch in Sunnyhills (first major subdivision), 1970s-80s ranch and two-story in Calaveras Hills against the foothills, 1990s-2000s production two-story in Murphy Ranch, and massive 2015+ apartment/condo near Milpitas BART',
    climateFactor: 'one of the WARMEST cities on this list — 85-95°F summers approaching San Jose east side temps. Receives heat from both inland valley and reflected from East Bay hills. Calaveras Fault runs directly through eastern Milpitas — higher seismic risk.',
    commonIssue: 'extreme UV and heat cycling damage to asphalt shingles on 1970s-80s homes — visible granule loss and curling. Stucco cracking on south/west walls from intense heat. Higher seismic risk makes roof-to-wall connections critical.',
    priceTier: 'premium',
    climateZone: 4,
    microclimate: 'Hot pocket at southern end of East Bay gap — warm air channels through Sunol Grade. 5-8°F warmer than Peninsula cities. Eastern Milpitas (Calaveras Hills) gets foothill cooling but more wind. Western (near 880/Great Mall) is hotter from heat island.',
    eraBreakdown: '3% pre-1960, 35% 1960-1980, 30% 1980-2000, 15% 2000-2010, 17% post-2010',
    roofingNote: 'Cool roof materials particularly important given extreme heat — reflective shingles (Owens Corning Duration COOL) reduce attic temps by 20-30°F. Ridge vent ventilation critical. Calaveras Hills homes should consider Class A even outside formal VHFHSZ. Solar common given high sun exposure.',
    sidingNote: 'Stucco dominant on 1980s+ homes. T1-11 on 1970s Sunnyhills and Augustine tracts is primary upgrade target. 1990s-2000s Murphy Ranch has builder-grade stucco needing maintenance. Some newer HOAs mandate specific color palettes.',
    windowNote: 'Extreme heat makes SHGC the critical rating — low solar heat gain more important here than almost anywhere in the county. Noise is MAJOR — I-880/680 interchange generates significant traffic noise. STC 35+ recommended near freeways.',
  },
];

/**
 * Look up a city by its URL slug.
 * Returns undefined if no match is found.
 */
export function getCitySeed(citySlug: string): CitySeed | undefined {
  return CITY_SEEDS.find((c) => c.slug === citySlug);
}

/**
 * Get all cities in a given county.
 */
export function getCitiesByCounty(countySlug: string): CitySeed[] {
  return CITY_SEEDS.filter((c) => c.countySlug === countySlug);
}

/**
 * All unique county slugs in the system.
 */
export const COUNTY_SLUGS = [
  ...new Set(CITY_SEEDS.map((c) => c.countySlug)),
] as const;
